/*
 * 1. Identificar las principales propiedades (atributos y métodos) de los siguientes objetos: 

a) Alumno.
b) Libro. 
c) Canción.
d) Televisor. 
e) Teléfono celular.
f)  Película. 
g) Mascota.
h) Curso. 
i)  Domicilio.
j)  Punto. 
k) Triángulo. 

Dar algunos ejemplos de instancias de las clases. 
 
Ejemplo:  
Clase: Rectangulo 
Atributos: base=3, altura=12, color=”verde”.

A) ALUMNO
CLASE: ALUMNO
ATRIBUTOS: NOMBRE, APELLIDO, EDAD
METODOS: MOSTRARNOTA.

B) LIBRO
ATRIBUTOS:TIRULO,COLOR,MATERIAL
METODOS:PASAR PAGINA

C)CANCION
ATRIBUTOS:NOMBRE,DURACION,ESTILO
METODOS:REPRODUCIR,PAUSAR

D)TELEVISOR
ATRIBUTOS:MARCA,PULGADAS,MATERIAL
METODOS:ENCENDER,APAGAR,SUBIR VOLUMEN

E)TELEFONO
ATRIBUTOS:MARCA,TAMAÑO,COLOR
METODOS:PRENDER,APAGAR,ABRIRINSTAGRAM

F)PELICULA
ATRIBUTOS:NOMBRE,DURACION,GENERO
METODOS:REPRODUCIR,PAUSAR,ACELERAR

G)MASCOTA
ATRIBUTOS:NOMBRE,RAZA,COLOR,SEXO,EDAD
METODOS:ACARICIAR,ALIMENTAR

H)DOMICILIO
ATRIBUTOS:ALTURA,NOMBREDECALLE
METODOS:CAMBIARNOMBRE

I)PUNTO
ATRIBUTOS:ALTURA,ANCHO
METODOS:CAMBIARPOSICION

J)TRIANGULO
ATRIBUTOS:LADO,ANGULOS
METODOS:CALCULARANGULOS.
 */

package Tp_2;

public class Punto_1 {
    
}
